In [15]:
import numpy as np

In [16]:
a = np.array([34, 25, 7])

print(a.shape)

(3,)


In [17]:
mat = np.random.random((3,3))
arreglo = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
print(mat, '\n')
print(arreglo)

[[0.43603083 0.51626976 0.90722773]
 [0.02680108 0.92966833 0.48729693]
 [0.28635764 0.97457809 0.3658347 ]] 

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [18]:
arreglo = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
diagonal = arreglo[[0, 1, 2], [0, 1, 2]]
print(diagonal)

[10 50 90]


In [19]:
arreglo = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
diagonal = arreglo[[0, 1, 2], [0, 1, 2]]
print(diagonal)

[10 50 90]


In [20]:
b = np.array([0, 1, 2])
arreglo = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
arreglo[np.arange(3), b] += 33
print(arreglo)
print(b.dtype)

[[ 43  20  30]
 [ 40  83  60]
 [ 70  80 123]]
int64


In [21]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8 , 9]])
c = np.array([[11, 22, 33], [44, 55, 66], [77, 88 , 99]])

d = np.multiply(a, b)
e = np.multiply(d, c)

print(e)

[[  110   880  2970]
 [ 7040 13750 23760]
 [37730 56320 80190]]


In [22]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8 , 9]])
c = np.array([[11, 22, 33], [44, 55, 66], [77, 88 , 99]])

d = np.multiply(a, (np.multiply(b, c)))



print(d)

[[  110   880  2970]
 [ 7040 13750 23760]
 [37730 56320 80190]]


In [23]:
a = np.random.random((3, 3))

print(a)

[[0.11718908 0.4491103  0.14737237]
 [0.47139648 0.01564152 0.07845667]
 [0.82453961 0.17239547 0.47812242]]


In [24]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8 , 9]])

print(a.dot(b))

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [25]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8 , 9]])



print(a.T)

[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [26]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.random.random(3)*100
c = np.empty_like(a)

print(a.shape)
print(b)

for i in range(3):
    c[i:] = a[i:] + b

print(c)

(3, 3)
[55.63978991 50.57874073 39.71542748]
[[ 65  70  69]
 [ 95 100  99]
 [125 130 129]]


In [27]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.random.random(3)*100

bb = np.tile(b, (3,1))
print(b, '\n')

c = a + bb

print(c)

[84.59071833 59.63699243 94.07747436] 

[[ 94.59071833  79.63699243 124.07747436]
 [124.59071833 109.63699243 154.07747436]
 [154.59071833 139.63699243 184.07747436]]


In [28]:
a = np.array([40, 50, 60, 70, 80])
b = np.random.random(4)*100

c = a + np.reshape(a, (5,1))

print((c.T + a).T)
print()
print(c)

[[120 130 140 150 160]
 [140 150 160 170 180]
 [160 170 180 190 200]
 [180 190 200 210 220]
 [200 210 220 230 240]]

[[ 80  90 100 110 120]
 [ 90 100 110 120 130]
 [100 110 120 130 140]
 [110 120 130 140 150]
 [120 130 140 150 160]]
