In [2]:
import numpy as np

In [3]:
a = np.array([34, 25, 7])

print(a.shape)

(3,)


In [4]:
mat = np.random.random((3,3))
arreglo = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
print(mat, '\n')
print(arreglo)

[[0.99208655 0.49750808 0.47568106]
 [0.8891108  0.67828187 0.58857682]
 [0.03274914 0.74159677 0.53976139]] 

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [5]:
arreglo = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
diagonal = arreglo[[0, 1, 2], [0, 1, 2]]
print(diagonal)

[10 50 90]


In [6]:
arreglo = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
diagonal = arreglo[[0, 1, 2], [0, 1, 2]]
print(diagonal)

[10 50 90]


In [7]:
b = np.array([0, 1, 2])
arreglo = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
arreglo[np.arange(3), b] += 33
print(arreglo)
print(b.dtype)

[[ 43  20  30]
 [ 40  83  60]
 [ 70  80 123]]
int64


In [8]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8 , 9]])
c = np.array([[11, 22, 33], [44, 55, 66], [77, 88 , 99]])

d = np.multiply(a, b)
e = np.multiply(d, c)

print(e)

[[  110   880  2970]
 [ 7040 13750 23760]
 [37730 56320 80190]]


In [9]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8 , 9]])
c = np.array([[11, 22, 33], [44, 55, 66], [77, 88 , 99]])

d = np.multiply(a, (np.multiply(b, c)))



print(d)

[[  110   880  2970]
 [ 7040 13750 23760]
 [37730 56320 80190]]


In [10]:
a = np.random.random((3, 3))

print(a)

[[0.00196551 0.9352987  0.82943895]
 [0.61360177 0.29701459 0.74629173]
 [0.14472466 0.46785936 0.95762029]]


In [11]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8 , 9]])

print(a.dot(b))

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


In [12]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8 , 9]])



print(a.T)

[[10 40 70]
 [20 50 80]
 [30 60 90]]


In [13]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.random.random(3)*100
c = np.empty_like(a)

print(a.shape)
print(b)

for i in range(3):
    c[i:] = a[i:] + b

print(c)

(3, 3)
[56.94973227 63.0592992  85.70285945]
[[ 66  83 115]
 [ 96 113 145]
 [126 143 175]]


In [14]:
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80 , 90]])
b = np.random.random(3)*100

bb = np.tile(b, (3,1))
print(b, '\n')

c = a + bb

print(c)

[ 8.76726907  3.47823195 26.89983099] 

[[ 18.76726907  23.47823195  56.89983099]
 [ 48.76726907  53.47823195  86.89983099]
 [ 78.76726907  83.47823195 116.89983099]]


In [15]:
a = np.array([40, 50, 60, 70, 80])
b = np.random.random(4)*100

c = a + np.reshape(a, (5,1))

print((c.T + a).T)
print()
print(c)

[[120 130 140 150 160]
 [140 150 160 170 180]
 [160 170 180 190 200]
 [180 190 200 210 220]
 [200 210 220 230 240]]

[[ 80  90 100 110 120]
 [ 90 100 110 120 130]
 [100 110 120 130 140]
 [110 120 130 140 150]
 [120 130 140 150 160]]
