In [2]:
import pandas as pd

In [3]:
ventas = pd.Series([15,12,21], index = ["Ene", "Feb", "Mar"])


In [4]:
ventas[1]

12

In [5]:
ventas['Ene']

15

In [6]:
ventas.dtype

dtype('int64')

In [7]:
ventas.values

array([15, 12, 21])

In [8]:
ventas.name = 'Ventas 2021'
ventas.name

'Ventas 2021'

In [9]:
ventas

Ene    15
Feb    12
Mar    21
Name: Ventas 2021, dtype: int64

In [10]:
ventas.index.name = 'Meses'

In [11]:
ventas

Meses
Ene    15
Feb    12
Mar    21
Name: Ventas 2021, dtype: int64

In [12]:
ventas.axes

[Index(['Ene', 'Feb', 'Mar'], dtype='object', name='Meses')]

In [13]:
ventas.shape

(3,)

In [14]:
import pandas as pd

In [15]:
datos = {'Manzanas' : [3, 2, 0, 1], 'Naranjas' : [0, 3, 7, 2]}

In [16]:
compras = pd.DataFrame(datos)
compras

Manzanas  Naranjas
0         3         0
1         2         3
2         0         7
3         1         2

In [17]:
compras = pd.DataFrame(datos, index = ['Juno', 'Robert', 'Lily', 'David'])
compras

Manzanas  Naranjas
Juno           3         0
Robert         2         3
Lily           0         7
David          1         2

In [18]:
compras.index

Index(['Juno', 'Robert', 'Lily', 'David'], dtype='object')

In [19]:
compras.columns

Index(['Manzanas', 'Naranjas'], dtype='object')

In [20]:
compras.axes

[Index(['Juno', 'Robert', 'Lily', 'David'], dtype='object'),
 Index(['Manzanas', 'Naranjas'], dtype='object')]

In [21]:
compras.index.name = 'Clientes'

In [22]:
compras.columns.name = 'Frutas'

In [23]:
compras

Frutas    Manzanas  Naranjas
Clientes                    
Juno             3         0
Robert           2         3
Lily             0         7
David            1         2

In [24]:
compras.values

array([[3, 0],
       [2, 3],
       [0, 7],
       [1, 2]])

In [25]:
compras.shape

(4, 2)

In [26]:
import pandas as pd

In [27]:
s = pd.Series([7, 5, 3], index = ['Enero', 'Febrero', 'Marzo'])
s

Enero      7
Febrero    5
Marzo      3
dtype: int64

In [28]:
d = {'Enero': 7, 'Febrero': 5, 'Marzo': 3}
s = pd.Series(d)
s

Enero      7
Febrero    5
Marzo      3
dtype: int64

In [29]:
s = pd.Series(d, index = ['Abril', 'Marzo', 'Febrero', 'Enero'], dtype=int)
s

Abril      NaN
Marzo      3.0
Febrero    5.0
Enero      7.0
dtype: float64

In [30]:
s = pd.Series(7, index = ['Enero', 'Febrero', 'Marzo', 'Abril'])
s

Enero      7
Febrero    7
Marzo      7
Abril      7
dtype: int64

In [31]:
datos = pd.Series([15, 16, 17, 18, 19], index = [ 'Libardo', 'Stella','Mauricio', 'Libardo A', 'Daniel'], name = 'Familia')
datos

Libardo      15
Stella       16
Mauricio     17
Libardo A    18
Daniel       19
Name: Familia, dtype: int64

In [32]:
datos['Mauricio']

17

In [33]:
datos[0]

15

In [34]:
datos.dtype

dtype('int64')

In [35]:
datos.index

Index(['Libardo', 'Stella', 'Mauricio', 'Libardo A', 'Daniel'], dtype='object')

In [36]:
datos.values

array([15, 16, 17, 18, 19])

In [37]:
datos.name = 'Familia 2021'
datos.name

'Familia 2021'

In [38]:
datos

Libardo      15
Stella       16
Mauricio     17
Libardo A    18
Daniel       19
Name: Familia 2021, dtype: int64

In [39]:
datos.index.name = 'Integrantes'
datos

Integrantes
Libardo      15
Stella       16
Mauricio     17
Libardo A    18
Daniel       19
Name: Familia 2021, dtype: int64

In [40]:
datos.axes

[Index(['Libardo', 'Stella', 'Mauricio', 'Libardo A', 'Daniel'], dtype='object', name='Integrantes')]

In [41]:
datos.shape

(5,)

In [42]:
familia = pd.DataFrame(datos)
familia

Familia 2021
Integrantes              
Libardo                15
Stella                 16
Mauricio               17
Libardo A              18
Daniel                 19

In [43]:
familia['Familia 2022'] = [55, 23, 67, 83, 21]
familia

Familia 2021  Familia 2022
Integrantes                            
Libardo                15            55
Stella                 16            23
Mauricio               17            67
Libardo A              18            83
Daniel                 19            21

In [44]:
familia.index

Index(['Libardo', 'Stella', 'Mauricio', 'Libardo A', 'Daniel'], dtype='object', name='Integrantes')

In [45]:
familia['Familia 2022']

Integrantes
Libardo      55
Stella       23
Mauricio     67
Libardo A    83
Daniel       21
Name: Familia 2022, dtype: int64

In [46]:
familia.columns

Index(['Familia 2021', 'Familia 2022'], dtype='object')

In [47]:
familia['Familia 2023'] = 0
familia

Familia 2021  Familia 2022  Familia 2023
Integrantes                                          
Libardo                15            55             0
Stella                 16            23             0
Mauricio               17            67             0
Libardo A              18            83             0
Daniel                 19            21             0

In [48]:
familia.index.name = 'Personas'
familia

Familia 2021  Familia 2022  Familia 2023
Personas                                           
Libardo              15            55             0
Stella               16            23             0
Mauricio             17            67             0
Libardo A            18            83             0
Daniel               19            21             0

In [49]:
familia.columns.name = 'Años'
familia

Años       Familia 2021  Familia 2022  Familia 2023
Personas                                           
Libardo              15            55             0
Stella               16            23             0
Mauricio             17            67             0
Libardo A            18            83             0
Daniel               19            21             0

In [50]:
familia.values

array([[15, 55,  0],
       [16, 23,  0],
       [17, 67,  0],
       [18, 83,  0],
       [19, 21,  0]])

In [51]:
familia.shape

(5, 3)

In [52]:
cumpleaños = pd.Series([9, 29, 9, 24, 22])
cumpleaños

0     9
1    29
2     9
3    24
4    22
dtype: int64

In [53]:
cumpleaños.index = ['Libardo', 'Stella', 'Mauricio', 'Libardo', 'Daniel']
cumpleaños

Libardo      9
Stella      29
Mauricio     9
Libardo     24
Daniel      22
dtype: int64

In [54]:
cumpleaños.index.name = 'Personas'
cumpleaños

Personas
Libardo      9
Stella      29
Mauricio     9
Libardo     24
Daniel      22
dtype: int64

In [55]:
productos = {'Tomate': [10, 73, 98, 12], 'Lechuga': [20, 74, 34, 56], 'Cebolla': [34, 33, 72, 90]}
viveres = pd.Series(productos, index = ['Papa', 'Tomate', 'Cebolla', 'Lechuga'], name = 'Enero')
viveres

Papa                    NaN
Tomate     [10, 73, 98, 12]
Cebolla    [34, 33, 72, 90]
Lechuga    [20, 74, 34, 56]
Name: Enero, dtype: object

In [56]:
productos

{'Tomate': [10, 73, 98, 12],
 'Lechuga': [20, 74, 34, 56],
 'Cebolla': [34, 33, 72, 90]}

In [57]:
tienda = pd.DataFrame(productos)
tienda

Tomate  Lechuga  Cebolla
0      10       20       34
1      73       74       33
2      98       34       72
3      12       56       90

In [58]:
tienda.index = ['Enero', 'Febrero', 'Marzo', 'Abril']
tienda.index.name = 'Meses'
tienda.columns.name = 'Productos'
tienda

Productos  Tomate  Lechuga  Cebolla
Meses                              
Enero          10       20       34
Febrero        73       74       33
Marzo          98       34       72
Abril          12       56       90

In [59]:
tienda = pd.DataFrame(productos, index = ['Marzo', 'Abril', 'Enero', 'Febrero'], columns = ['Cebolla', 'Tomate', 'Lechuga'])
tienda

Cebolla  Tomate  Lechuga
Marzo         34      10       20
Abril         33      73       74
Enero         72      98       34
Febrero       90      12       56

In [60]:
import numpy as np

In [61]:
unidades_datos = np.array([[1, 2, 3, 5], [4, 6, 7, 2], [3, 2, 4, 1]])
unidades_datos

array([[1, 2, 3, 5],
       [4, 6, 7, 2],
       [3, 2, 4, 1]])

In [62]:
unidades = pd.DataFrame(unidades_datos)
unidades

0  1  2  3
0  1  2  3  5
1  4  6  7  2
2  3  2  4  1

In [63]:
unidades = pd.DataFrame(unidades_datos, index = ['AB+', 'O+', 'B+'], columns=[2015, 2016, 2017, 2018])
unidades

2015  2016  2017  2018
AB+     1     2     3     5
O+      4     6     7     2
B+      3     2     4     1

In [64]:
centro_vic = {'Ropa': 3, 'Zapatos': 5, 'Accesorios': 7}
centro_per = {'Ropa': 2, 'Zapatos': 2, 'Accesorios': 6}
centro_bol = {'Ropa': 8, 'Zapatos': 3, 'Accesorios': 2}

centros_comerciales = pd.DataFrame([centro_vic, centro_per, centro_bol], index = ['Victoria', 'Per_plaza', 'Bolivar'])
centros_comerciales

Ropa  Zapatos  Accesorios
Victoria      3        5           7
Per_plaza     2        2           6
Bolivar       8        3           2

In [65]:
unicentro = pd.Series([12, 8, 10, 15, 5, 12, 17, 20], index = ['Nike', 'Adidas', 'Rebook', 'Puma', 'UnderArmour', 'Salomon', 'Fila', 'Arcterix'])
unicentro

Nike           12
Adidas          8
Rebook         10
Puma           15
UnderArmour     5
Salomon        12
Fila           17
Arcterix       20
dtype: int64

In [66]:
arboleda = pd.Series([34, 21, 7, 2, 3, 12, 4, 6], index = ['Puma', 'Adidas', 'Nike', 'Rebook', 'UnderArmour', 'Salomon', 'Fila', 'Arcterix'])
arboleda

Puma           34
Adidas         21
Nike            7
Rebook          2
UnderArmour     3
Salomon        12
Fila            4
Arcterix        6
dtype: int64

In [67]:
ventas = pd.DataFrame({'Arboleda': arboleda, 'Unicentro': unicentro})
ventas['Total'] = arboleda + unicentro
ventas

Arboleda  Unicentro  Total
Adidas             21          8     29
Arcterix            6         20     26
Fila                4         17     21
Nike                7         12     19
Puma               34         15     49
Rebook              2         10     12
Salomon            12         12     24
UnderArmour         3          5      8

In [68]:
ventas.sample(4) #aleatorio

Arboleda  Unicentro  Total
Rebook           2         10     12
Fila             4         17     21
Puma            34         15     49
Arcterix         6         20     26

In [69]:
ventas.head()

Arboleda  Unicentro  Total
Adidas          21          8     29
Arcterix         6         20     26
Fila             4         17     21
Nike             7         12     19
Puma            34         15     49

In [70]:
ventas.tail()

Arboleda  Unicentro  Total
Nike                7         12     19
Puma               34         15     49
Rebook              2         10     12
Salomon            12         12     24
UnderArmour         3          5      8

In [71]:
ventas

Arboleda  Unicentro  Total
Adidas             21          8     29
Arcterix            6         20     26
Fila                4         17     21
Nike                7         12     19
Puma               34         15     49
Rebook              2         10     12
Salomon            12         12     24
UnderArmour         3          5      8

In [72]:
ventas.describe()

Arboleda  Unicentro      Total
count   8.000000   8.000000   8.000000
mean   11.125000  12.375000  23.500000
std    11.115465   4.867898  12.455636
min     2.000000   5.000000   8.000000
25%     3.750000   9.500000  17.250000
50%     6.500000  12.000000  22.500000
75%    14.250000  15.500000  26.750000
max    34.000000  20.000000  49.000000

In [73]:
ventas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, Adidas to UnderArmour
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Arboleda   8 non-null      int64
 1   Unicentro  8 non-null      int64
 2   Total      8 non-null      int64
dtypes: int64(3)
memory usage: 256.0+ bytes


In [74]:
ventas['Unicentro'].value_counts()

12    2
15    1
10    1
8     1
5     1
20    1
17    1
Name: Unicentro, dtype: int64

In [75]:
ventas[3:7]

Arboleda  Unicentro  Total
Nike            7         12     19
Puma           34         15     49
Rebook          2         10     12
Salomon        12         12     24

In [76]:
ventas.shape

(8, 3)

In [77]:
ventas.loc['Puma']

Arboleda     34
Unicentro    15
Total        49
Name: Puma, dtype: int64

In [78]:
ventas.iloc[0:2]

Arboleda  Unicentro  Total
Adidas          21          8     29
Arcterix         6         20     26

In [79]:
ventas['Arboleda']['Adidas'] # Primero hay que poner las columnas

21

In [80]:
ventas['Bolivar'] = pd.Series([10, 23, 13, 24, 9, 4, 8, 6], index = ['Nike', 'Adidas', 'Arcterix', 'Puma', 'Fila', 'Rebook', 'Salomon', 'UnderArmour'])
ventas

Arboleda  Unicentro  Total  Bolivar
Adidas             21          8     29       23
Arcterix            6         20     26       13
Fila                4         17     21        9
Nike                7         12     19       10
Puma               34         15     49       24
Rebook              2         10     12        4
Salomon            12         12     24        8
UnderArmour         3          5      8        6

In [81]:
ventas['Total'] = ventas['Arboleda'] + ventas['Unicentro'] + ventas['Bolivar']
ventas

Arboleda  Unicentro  Total  Bolivar
Adidas             21          8     52       23
Arcterix            6         20     39       13
Fila                4         17     30        9
Nike                7         12     29       10
Puma               34         15     73       24
Rebook              2         10     16        4
Salomon            12         12     32        8
UnderArmour         3          5     14        6

In [82]:
ventas.pop('Total')
ventas

Arboleda  Unicentro  Bolivar
Adidas             21          8       23
Arcterix            6         20       13
Fila                4         17        9
Nike                7         12       10
Puma               34         15       24
Rebook              2         10        4
Salomon            12         12        8
UnderArmour         3          5        6

In [83]:
ventas['Total'] = ventas['Arboleda'] + ventas['Unicentro'] + ventas['Bolivar']
ventas

Arboleda  Unicentro  Bolivar  Total
Adidas             21          8       23     52
Arcterix            6         20       13     39
Fila                4         17        9     30
Nike                7         12       10     29
Puma               34         15       24     73
Rebook              2         10        4     16
Salomon            12         12        8     32
UnderArmour         3          5        6     14

In [84]:
ventas.axes

[Index(['Adidas', 'Arcterix', 'Fila', 'Nike', 'Puma', 'Rebook', 'Salomon',
        'UnderArmour'],
       dtype='object'),
 Index(['Arboleda', 'Unicentro', 'Bolivar', 'Total'], dtype='object')]

In [85]:
ventas.index.name = 'Marcas'
ventas.columns.name = 'C.Comerciales'

In [86]:
ventas

C.Comerciales  Arboleda  Unicentro  Bolivar  Total
Marcas                                            
Adidas               21          8       23     52
Arcterix              6         20       13     39
Fila                  4         17        9     30
Nike                  7         12       10     29
Puma                 34         15       24     73
Rebook                2         10        4     16
Salomon              12         12        8     32
UnderArmour           3          5        6     14

In [87]:
import pandas as pd

In [88]:
df = pd.DataFrame(np.random.randint(0, 10, 24).reshape(6, 4), index = ['a', 'b', 'c', 'd', 'e', 'f'], columns = ['A', 'Basico', 'C', 'D'])
df

A  Basico  C  D
a  4       5  1  2
b  3       3  5  6
c  1       3  5  6
d  1       7  0  4
e  2       1  6  6
f  5       5  0  1

In [89]:
df.iloc[df.index.get_loc('c'), 2]

5

In [90]:
df.columns.get_loc('D') # Devuelve la posicion de la columna

3

In [91]:
df.columns.get_indexer(['B', 'C']) # Devuelve un array con las posiciones

array([-1,  2])

In [92]:
df.index.get_loc('d') # Devuelve la posicion del indice

3

In [93]:
df.index.get_indexer(['c', 'e']) # Devuelve un array con las posiciones de los indices

array([2, 4])

In [94]:
df.iloc[df.index.get_loc('c'), 3] # devuleve el valor indice 'c' columna 3

6

In [95]:
df.iloc[[3, 5], df.columns.get_indexer(['C', 'A'])]

C  A
d  0  1
f  0  5

In [96]:
mask = [True, False, True, False, False, True]
df[mask]

A  Basico  C  D
a  4       5  1  2
c  1       3  5  6
f  5       5  0  1

In [97]:
df[df.Basico > 5]

A  Basico  C  D
d  1       7  0  4

In [98]:
df.loc[df.Basico > 5]

A  Basico  C  D
d  1       7  0  4

In [99]:
df.iloc[(df.Basico > 5).values]

A  Basico  C  D
d  1       7  0  4